services:
  server:
    image: ghcr.io/ironcalc/ironcalc-server:0.7.1
    build:
      context: .
      target: server-runtime

  caddy:
    image: ghcr.io/ironcalc/ironcalc-caddy:0.7.1
    build:
      context: .
      target: caddy-runtime
    ports:
      - "2080:2080"
