[package]
name = "ironcalc-dotnet"
version = "0.0.1-beta1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ironcalc = { path = "../../xlsx" }

[build-dependencies]
csbindgen = "1.9.6"
